--DATA PREPARATION AND UNDERSTANDING
--Q1.What is the total number of rows in each of the 3 tables in the database?
SELECT COUNT(*) FROM Customer
SELECT COUNT(*) FROM prod_cat_info 
SELECT COUNT(*) FROM Transactions

--Q2.What is the total number of transactions that have a return?
SELECT COUNT (*) FROM Transactions 
WHERE total_amt<1

--Q3.As you would have noticed, the dates provided across the datasets are not
--in a correct format. As first steps, pls convert the date variables into valid 
--date formats before proceeding ahead

SELECT CONVERT(DATE, DOB, 105) AS DATES FROM Customer 
SELECT CONVERT(DATE, tran_date, 105) AS TRAN_DATES FROM Transactions

--Q4.What is the time range of the transaction data available for analysis?
--Show the output in number of days, months and years simultaneously in different columns.

SELECT DATEDIFF(DAY, MIN(CONVERT(DATE, TRAN_DATE, 105)), MAX(CONVERT(DATE, TRAN_DATE, 105))), 
DATEDIFF(MONTH, MIN(CONVERT(DATE, TRAN_DATE, 105)), MAX(CONVERT(DATE, TRAN_DATE, 105))),  
DATEDIFF(YEAR, MIN(CONVERT(DATE, TRAN_DATE, 105)), MAX(CONVERT(DATE, TRAN_DATE, 105))) 
FROM TRANSACTIONS

--Q5.Which product category does the sub-category “DIY” belong to?
SELECT prod_cat FROM prod_cat_info
WHERE prod_subcat='DIY'

--DATA ANALYSIS


--Q1.Which channel is most frequently used for transactions?

SELECT TOP 1 Store_type, COUNT(*) AS TransactionCount
FROM Transactions
GROUP BY Store_type
ORDER BY TransactionCount DESC



--Q2.What is the count of Male and Female customers in the database?

 select Gender,COUNT(*) as "count of customer" from Customer
 where Gender in ('m','f')
 group by Gender

--Q3.From which city do we have the maximum number of customers and how many?

 select top 1 city_code,COUNT(*)  as "no.of customer" from Customer
 group by city_code
 order by "no.of customer" desc
 
--Q4.How many sub-categories are there under the Books category?
 
 SELECT prod_cat,count(*) as "no.of subcategory" from prod_cat_info
 where prod_cat='books'
 group by prod_cat
 
--Q5.What is the maximum quantity of products ever ordered?
 
SELECT TOP 1 Qty
FROM Transactions
ORDER BY Qty DESC
 
--Q6.What is the net total revenue generated in categories Electronics and Books?
 
 select prod_cat,sum(total_amt) from Transactions as x
 inner join prod_cat_info as y
 on x.prod_cat_code = y.prod_cat_code
 where prod_cat in ('electronics','books')
 group by prod_cat

--Q7.How many customers have >10 transactions with us, excluding returns?

SELECT COUNT(customer_Id) AS CUSTOMER_COUNT
FROM Customer WHERE CUSTOMER_ID IN 
	(
		SELECT cust_id
		FROM Transactions
		LEFT JOIN Customer 
		ON customer_Id = cust_id
		WHERE total_amt not like'-%'
		GROUP BY cust_id
		HAVING COUNT(transaction_id) > 10
)

--Q8.What is the combined revenue earned from the “Electronics” & “Clothing” 
--categories,from “Flagship stores”?

SELECT SUM(total_amt) AS AMOUNT FROM Transactions AS T1
INNER JOIN prod_cat_info AS T2
ON T1.prod_cat_code = T2.prod_cat_code 
	  AND T1.prod_subcat_code = T2.prod_sub_cat_code
WHERE prod_cat IN ('CLOTHING','ELECTRONICS') AND Store_type = 'FLAGSHIP STORE'

--Q9.What is the total revenue generated from “Male” customers in “Electronics” category?
--Output should display total revenue by prod sub-cat.

SELECT prod_subcat,SUM(total_amt) AS TOTAL_REVENUE FROM Transactions AS T1
LEFT JOIN Customer AS T2
ON T1.cust_id=T2.customer_Id
LEFT JOIN prod_cat_info AS T3
ON T1.prod_cat_code=T3.prod_cat_code
AND T1.prod_subcat_code=T3.prod_sub_cat_code
WHERE T3.prod_cat='ELECTRONICS' AND T2.Gender='M'
GROUP BY T3.prod_subcat

--Q10.What is percentage of sales and returns by product sub category;
--display only top 5 sub categories in terms of sales?

select prod_subcat,round((total_sales/(total_sales+total_return)*100),2) as [sales%tage],
round((total_return/(total_sales+total_return)*100),2) as [return%tage]
from
(
	SELECT  top 5 prod_subcat,
	sum (CASE WHEN total_amt> 0 THEN total_amt ELSE 0 END) AS total_sales,
	sum (CASE WHEN total_amt< 0 THEN abs(total_amt) ELSE 0 END) AS total_return
	FROM Transactions trans
	INNER JOIN prod_cat_info pci
	ON
	trans.prod_cat_code=pci.prod_cat_code
	AND
	PROD_SUBCAT_CODE= prod_sub_cat_code
	GROUP BY PROD_SUBCAT
	ORDER BY PROD_SUBCAT DESC
)as X



--Q11.	For all customers aged between 25 to 35 years 
--find what is the net total revenue generated by these consumers in last 30 days of 
--transactions from max transaction

SELECT CUST_ID,SUM(TOTAL_AMT) AS REVENUE FROM Transactions
WHERE CUST_ID IN 
	(SELECT CUSTOMER_ID
	 FROM Customer
     WHERE DATEDIFF(YEAR,CONVERT(DATE,DOB,103),GETDATE()) BETWEEN 25 AND 35)
     AND CONVERT(DATE,tran_date,103) BETWEEN DATEADD(DAY,-30,
	 (SELECT MAX(CONVERT(DATE,tran_date,103)) FROM Transactions)) 
	 AND (SELECT MAX(CONVERT(DATE,tran_date,103)) FROM Transactions)
GROUP BY CUST_ID

--Q12.	Which product category has seen the max value of returns in the 
--last 3 months of transactions?

SELECT TOP 1 PROD_CAT, SUM(total_amt) as Total FROM Transactions as T1
INNER JOIN prod_cat_info as T2 ON T1.prod_cat_code = T2.prod_cat_code 
AND T1.prod_subcat_code = T2.prod_sub_cat_code
WHERE TOTAL_AMT < 0 AND 
CONVERT(date, tran_date, 103) BETWEEN DATEADD(MONTH,-3,
(SELECT MAX(CONVERT(DATE,tran_date,103)) FROM Transactions)) 
AND (SELECT MAX(CONVERT(DATE,tran_date,103)) FROM Transactions)
GROUP BY PROD_CAT
ORDER BY 2 DESC

--Q13.	Which store-type sells the maximum products; by value of sales amount 
--and by quantity sold?

SELECT  Store_type, SUM(total_amt) as TOT_SALES, 
SUM(Qty) as TOT_QUAN FROM Transactions
GROUP BY Store_type
HAVING SUM(total_amt) >=ALL (SELECT SUM(total_amt) FROM Transactions 
GROUP BY Store_type)
AND SUM(Qty) >=ALL (SELECT SUM(Qty) FROM Transactions 
GROUP BY Store_type
)

--Q14.	What are the categories for which average revenue is above the overall average.

SELECT prod_cat, AVG(TOTAL_AMT) AS AVERAGE
FROM Transactions as T1
INNER JOIN prod_cat_info as T2 
ON T2.prod_cat_code=T1.prod_cat_code 
AND T2.prod_sub_cat_code=T1.prod_subcat_code
GROUP BY PROD_CAT
HAVING AVG(TOTAL_AMT)>(SELECT AVG(TOTAL_AMT) FROM Transactions)


--Q15.	Find the average and total revenue by each subcategory for the categories 
--which are among top 5 categories in terms of quantity sold

SELECT top 5 t2.prod_cat, t2.prod_subcat, AVG(total_amt) AS AVERAGE_REV, SUM(total_amt) AS REVENUE
FROM Transactions as t1
INNER JOIN prod_cat_info as t2
ON t2.prod_cat_code=t1.prod_cat_code 
AND t1.prod_subcat_code=t2.prod_sub_cat_code
WHERE t2.prod_cat IN
(
SELECT top 5
t2.prod_cat
FROM Transactions as t1 
INNER JOIN prod_cat_info as t2
ON t1.prod_cat_code=t2.prod_cat_code 
AND t2.prod_sub_cat_code = t1.prod_subcat_code
GROUP BY t2.prod_cat
ORDER BY SUM(QTY) DESC
)
GROUP BY t2.prod_cat, t2.prod_subcat